# Generated by Django 4.2.6 on 2023-10-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('Id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('DeliveryPercent', models.IntegerField(verbose_name='Delivery Percent')),
                ('EvaluationType', models.CharField(max_length=50, verbose_name='Description')),
                ('PriceChangesPercent', models.IntegerField(verbose_name='Price Changes Percent')),
                ('QualityPercent', models.IntegerField(verbose_name='Quality Percent')),
                ('ServicePercent', models.IntegerField(verbose_name='Quality Percent')),
            ],
        ),
    ]
