# Generated by Django 4.2.6 on 2023-10-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VPEApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evaluationtype',
            table='VPEApp_evaluationtype',
        ),
    ]
