# Generated by Django 4.2.6 on 2023-10-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VPEApp', '0002_alter_evaluationtype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evaluationtype',
            table='Evaluationtype',
        ),
    ]
