# Generated by Django 4.2.6 on 2023-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPEApp', '0004_alter_evaluationtype_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersList',
            fields=[
                ('Id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('GlobalId', models.IntegerField(verbose_name='Global Id')),
                ('Name', models.CharField(max_length=500, verbose_name='Name')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
