# Generated by Django 4.2.6 on 2023-10-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPEApp', '0006_alter_userslist_globalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslist',
            name='Id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
