# Generated by Django 4.2.6 on 2023-10-12 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('VPEApp', '0007_alter_userslist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationtype',
            name='Id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userslist',
            name='Id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
